# Generated by Django 4.0.3 on 2022-05-05 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WTR', 'drinking water'), ('WLK', 'walking'), ('REA', 'reading books'), ('SLP', 'sleeping'), ('EAT', 'eating meals'), ('SPO', 'train or exercise')], default='WTR', max_length=3)),
                ('interval', models.CharField(choices=[('DAY', 'day'), ('WEE', 'week'), ('MTH', 'month')], default='DAY', max_length=3)),
                ('freq', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('remind', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
